# Generated by Django 6.0.5 on 2026-06-03 10:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100))),
                ('description', models.CharField(max_length=200)),
                ('jlpt_level', models.CharField(choices=[('N1', 'JLPT_N1'), ('N2', 'JLPT_N2'), ('N3', 'JLPT_N3'), ('N4', 'JLPT_N4'), ('N5', 'JLPT_N5')], max_length=3)),
                ('grammars', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100))),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
