# Generated by Django 6.0.5 on 2026-07-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_content_alter_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='banner_image',
            field=models.ImageField(default='default/japan-banner.jpg', upload_to='blog_banner'),
        ),
    ]
