# Generated by Django 6.0.5 on 2026-07-12 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='grammars',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
    ]
