# Generated by Django 6.0.5 on 2026-07-27 08:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_remove_blog_grammars_remove_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='grammars',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('X wa Y desu', 'X wa Y desu'), ('-ka (Question marker)', '-ka (Question marker)'), ('no (Possessive/of)', 'no (Possessive/of)'), ('Numbers', 'Numbers'), ('kosoado', 'kosoado'), ('mo', 'mo (Also/too)'), ('desu conjugation', 'desu conjugation'), ('~ne / ~yo', '~ne / ~yo'), ('Verb casual form & verb categories', 'Verb casual form & verb categories'), ('polite form conjugation', 'polite form conjugation'), ('Subject wa Object o Activity', 'Subject wa Object o Activity'), ('Subject wa Place de Object o Activity', 'Subject wa Place de Object o Activity'), ('Subject wa Place ni iku / kuru / kaeru', 'Subject wa Place ni iku / kuru / kaeru'), ('Date/Time ni Subject wa Place de Object o Activity', 'Date/Time ni Subject wa Place de Object o Activity'), ('~masen ka', '~masen ka'), ('Frequency Adverbs', 'Frequency Adverbs'), ('Topic particle wa', 'Topic particle wa'), ('X ga arimasu / imasu', 'X ga arimasu / imasu'), ('Describing where things are', 'Describing where things are'), ('Duration', 'Duration'), ('takusan', 'takusan'), ('to', 'to'), ('Adjectives (i and na)', 'Adjectives (i and na)'), ('~mashou / mashou ka', '~mashou / mashou ka'), ('Counting', 'Counting'), ('~te, ~.', '~te, ~. (Combining activities)'), ('~te kudasai', '~te kudasai (Asking for favour)'), ('~te mo ii desu (Permission)', '~te mo ii desu (Permission)'), ('~te wa ikemasen', '~te wa ikemasen (Must not)'), ('~kara', '~kara (Because)'), ('~mashou ka', '~mashou ka'), ('converting adjectives into adverbs', 'converting adjectives into adverbs'), ('doumo', 'doumo'), ('o (Honorific prefix)', 'o (Honorific prefix)'), ('~te imasu', '~te imasu'), ('body part ga ~ desu', 'body part ga ~ desu'), ('Te forms for joining sentences', 'Te forms for joining sentences'), ('verb stem + ni iku', 'verb stem + ni iku'), ('~nin', '~nin'), ('shiru / wakaru', 'shiru / wakaru'), ('~to omoimasu', '~to omoimasu'), ('~to itte imashita', '~to itte imashita'), ('~naide kudasai', '~naide kudasai'), ('casual form no ga suki desu', 'casual form no ga suki desu'), ('ga', 'ga'), ('nanika / nanimo', 'nanika / nanimo'), ('Past tense verbs', 'Past tense verbs'), ('descriptive part', 'descriptive part'), ('mada ~te imasen', 'mada ~te imasen'), ('A no hou ga B yori adjective desu', 'A no hou ga B yori adjective desu'), ('A to B to dochira no hou / docchi no hou ga adjective', 'A to B to dochira no hou / docchi no hou ga adjective'), ('group de / no naka de A ga ichiban adjective', 'group de / no naka de A ga ichiban adjective'), ('no (one)', 'no (one)'), ('~tsumori desu', '~tsumori desu'), ('adjective + naru', 'adjective + naru'), ('dokoka ni / doko ni mo', 'dokoka ni / doko ni mo'), ('method + de', 'method + de'), ('~tai desu (Desire)', '~tai desu (Desire)'), ('~tari ~tari suru', '~tari ~tari suru'), ('~koto ga aru (Have done before)', '~koto ga aru (Have done before)'), ('noun A ya noun B', 'noun A ya noun B'), ('~n desu', '~n desu'), ('~sugiru (Too much)', '~sugiru (Too much)'), ('~hou ga ii desu (Advice)', '~hou ga ii desu (Advice)'), ('~node', '~node'), ('~nakereba ikemasen / ~nakya ikemasen', '~nakereba ikemasen / ~nakya ikemasen'), ('~deshou', '~deshou'), ('potential verbs', 'potential verbs'), ('~shi', '~shi'), ('~sou desu (It looks like...)', '~sou desu (It looks like...)'), ('~te miru', '~te miru'), ('nara', 'nara'), ('isshuukan ni sankai', 'isshuukan ni sankai'), ('hoshii', 'hoshii'), ('~kamoshiremasen', '~kamoshiremasen'), ('ageru / kureru / morau', 'ageru / kureru / morau'), ('~tara dou desu ka', '~tara dou desu ka'), ('Number + mo / Number + shika + Negative', 'Number + mo / Number + shika + Negative'), ('Volitional Form', 'Volitional Form'), ('Volitional Form + to omotte imasu', 'Volitional Form + to omotte imasu'), ('~te oku', '~te oku'), ('~te itadakemasen ka', '~te itadakemasen ka'), ('~to ii', '~to ii'), ('~toki', '~toki'), ('~te sumimasen deshita', '~te sumimasen deshita'), ('~sou desu (It looks like)', '~sou desu (It looks like)'), ('tara', 'tara'), ('nakute mo ii desu', 'nakute mo ii desu'), ('~te shimau (Accidentally)', '~te shimau (Accidentally)'), ('~nagara (While doing)', '~nagara (While doing)'), ('~yasui / ~nikui (Easy/Difficult to do)', '~yasui / ~nikui (Easy/Difficult to do)'), ('~te kureru / ~te morau (Receiving favors)', '~te kureru / ~te morau (Receiving favors)'), ('Passive form', 'Passive form'), ('Causative form', 'Causative form'), ('~ba (Conditional)', '~ba (Conditional)')], max_length=1000), default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('anime', 'Anime'), ('arts', 'Arts'), ('business', 'Business'), ('culture', 'Culture'), ('food', 'Food'), ('fashion', 'Fashion'), ('games', 'Games'), ('movies', 'Movies'), ('sports', 'Sports'), ('tech', 'Technology'), ('travel', 'Travel')], max_length=100), default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='jlpt_level',
            field=models.CharField(choices=[('N1', 'JLPT N1'), ('N2', 'JLPT N2'), ('N3', 'JLPT N3'), ('N4', 'JLPT N4'), ('N5', 'JLPT N5')], max_length=3),
        ),
    ]
